
package ro.stefanprisca.distsystems.utils.login.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.2
 * Fri Nov 07 20:12:07 EET 2014
 * Generated source version: 3.0.2
 */

@XmlRootElement(name = "deleteUserResponse", namespace = "http://login.utils.distsystems.stefanprisca.ro/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteUserResponse", namespace = "http://login.utils.distsystems.stefanprisca.ro/")

public class DeleteUserResponse {


}

