
package ro.stefanprisca.distsystems.utils.login.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.2
 * Fri Nov 07 18:43:04 EET 2014
 * Generated source version: 3.0.2
 */

@XmlRootElement(name = "doLogin", namespace = "http://login.utils.distsystems.stefanprisca.ro/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "doLogin", namespace = "http://login.utils.distsystems.stefanprisca.ro/", propOrder = {"arg0", "arg1"})

public class DoLogin {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

}

