
package ro.stefanprisca.distsystems.utils.login.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sun Nov 23 16:43:48 EET 2014
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "getUsersResponse", namespace = "http://login.utils.distsystems.stefanprisca.ro/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUsersResponse", namespace = "http://login.utils.distsystems.stefanprisca.ro/")

public class GetUsersResponse {

    @XmlElement(name = "return")
    private java.util.List<ro.stefanprisca.distsystems.utils.login.models.ApplicationUser> _return;

    public java.util.List<ro.stefanprisca.distsystems.utils.login.models.ApplicationUser> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<ro.stefanprisca.distsystems.utils.login.models.ApplicationUser> new_return)  {
        this._return = new_return;
    }

}

