//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATIONUSER
    {
        public decimal ID { get; set; }
        public string BIRTHDATE { get; set; }
        public string HOMEADDRESS { get; set; }
        public string LATITUDE { get; set; }
        public string LOGINID { get; set; }
        public string LOGINPW { get; set; }
        public string LONGITUDE { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
    }
}
